# Config file for automatic testing at travis-ci.org

dist: bionic
sudo: required
language: python
python:
  - "3.6"
  - "3.7"
services:
  - postgresql

env:
  - TOX_ENV=django-111
  - TOX_ENV=django-20
  - TOX_ENV=django-21
  - TOX_ENV=django-22
  - TOX_ENV=django-30

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
